import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
    subsets: ["latin"],
    weight: ["400", "600", "700"], // Add weights you need
    variable: "--font-outfit",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${outfit.variable} antialiased`}>
                <div className="fixed top-0 w-full flex justify-between py-8 px-14 text-base">
                    <p>LOGO</p>
                    <ul className="flex space-x-14">
                        <li className="cursor-pointer">Home</li>
                        <li className="cursor-pointer">About</li>
                        <li className="cursor-pointer">Project</li>
                        <li className="cursor-pointer">Contact</li>
                    </ul>
                </div>
                {children}
            </body>
        </html>
    );
}
